spring.application.name=backend

# 資料庫連線設定
spring.datasource.url=jdbc:mysql://localhost:3306/log_db?serverTimezone=Asia/Taipei&characterEncoding=utf-8

spring.datasource.username=root
spring.datasource.password=root

# Hibernate 自動建立資料表
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 看到 ? 填入什麼資料
logging.level.org.hibernate.orm.jdbc.bind=trace

# 讓 Hibernate 生成更精準的 SQL 語法
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# SQL 語句排版漂亮一點
spring.jpa.properties.hibernate.format_sql=true

# Log 訊息有顏色
spring.output.ansi.enabled=ALWAYS